### ISSUE TITLE
Improvement: Different transistor to allow lower voltages

### ISSUE THREAD

**Issue by matthijskooijman** [madworm/AVR-ISP_level-shifter#1]
The currently used 2N7000 has a gate threshold of 0.8V - 3.0V, so it might not work on voltages below 3.0V. Using a transistor with a lower gate threshold might allow a wider range of operating voltages.

Perhaps the BSS138 is suitable? It is SMD, but has 1.3V typical and 1.5V max. It is also used in [this similar project](https://github.com/madworm/AVR-ISP_level-shifter).

**Comment by madworm** [comment]
The last time I looked, this project used the BSS138 (see the schematic) :-)

**Comment by matthijskooijman** [comment]
Heh, I was planning to create these two tickets in my own repo (https://github.com/matthijskooijman/FtdiTranslator) which contains a similar design for an FTDI-compatible serial connector, referring to this repo, but it seemed I messed that up :-P

So, this ticket is completely pointless and can be closed, the other one is apparently a useful suggestion, so I'll leave it open.

**Comment by madworm** [comment]
No worries :-)
